name: deploy

on:
  push:
    branches:
      - master
    tags:
      - '**'

permissions:
  contents: write

jobs:
  test-and-deploy:
    runs-on: self-hosted
    container: jhhlab/tgsaap-firmware:latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: build
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE=Debug \
          -DDOC=ON \
          -DGCOV=ON
        make -j -C build
    - name: run unit-test
      run: |
        make test -C build
    - name: generate code coverage
      run: |
        make -C build coverage
    - name: generate deb package
      run: |
        cd build && cpack
    - name: prepare release
      run: |
        mkdir release
        mv build/coverage         release/coverage
        mv build/doc/doxygen/html release/document
        mv build/*.deb            release/
    - name: generate release tag
      id: tag
      run: echo "release_tag=$(date +"%Y.%m.%d_%H-%M")" >> $GITHUB_OUTPUT
    - name: Release data
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ github.token }}
        make_latest: true
        tag_name: ${{ steps.tag.outputs.release_tag }}
        target_commitish: ${{ github.sha }}
        files: release/*.deb
    - name: pack artifact
      run: |
        cd release
        zip -r ../release.zip *
    - name: deploy document and coverage
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      env:
        deploy_path: ${{ secrets.DEPLOY_WORK_DIR }}/${{ github.repository }}/${{ github.ref_type }}/${{ github.ref_name }}
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        user: ${{ secrets.DEPLOY_USER }}
        port: ${{ secrets.DEPLOY_PORT }}
        key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        first_ssh: |
          mkdir -p $deploy_path
          rm -rf $deploy_path/*
        scp: |
          release.zip => $deploy_path/
        last_ssh: |
          cd $deploy_path
          unzip release.zip
          rm release.zip
