name: preview

permissions:
  pull-requests: write
  contents: write

on: pull_request

jobs:
  test-and-deploy:
    runs-on: self-hosted
    container: jhhlab/tgsaap-firmware:latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: build
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE=Debug \
          -DDOC=ON \
          -DGCOV=ON
        make -j -C build
    - name: run unit-test
      run: |
        make test -C build
    - name: generate code coverage
      run: |
        make -C build coverage
    - name: prepare release
      run: |
        mkdir release
        mv build/coverage         release/coverage
        mv build/doc/doxygen/html release/document
    - name: pack artifact
      run: |
        cd release
        zip -r ../release.zip *
    - name: deploy document and coverage
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      env:
        preview_path: ${{ secrets.DEPLOY_WORK_DIR }}/${{ github.repository }}/preview/${{ github.event.number }}
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        user: ${{ secrets.DEPLOY_USER }}
        port: ${{ secrets.DEPLOY_PORT }}
        key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        first_ssh: |
          mkdir -p $preview_path
          rm -rf $preview_path/*
        scp: |
          release.zip => $preview_path/
        last_ssh: |
          cd $preview_path
          unzip release.zip
          rm release.zip
    - name: find comment
      uses: peter-evans/find-comment@v2
      id: find-comment
      with:
        issue-number: ${{ github.event.number }}
        comment-author: 'github-actions[bot]'
    - name: update comment
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.number }}
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        edit-mode: replace
        body: |
          https://${{ secrets.DEPLOY_HOST }}/${{ github.repository }}/preview/${{ github.event.number }}
